global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Go Application
  - job_name: 'go-grafana-app'
    static_configs:
      - targets: ['app:8080']
    metrics_path: '/api/v1/metrics'
    scrape_interval: 5s
    scrape_timeout: 3s
    honor_labels: true 